/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_form;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import java.util.Random;

/**
 *
 * @author desalegn
 */
public class login extends javax.swing.JFrame {
   String Password;
        String Username;
        String LastName;
        String Email; 
        
    String [][]authhuser={{Username, Password}};
/*
  
        * Creates new form login
     */
    public login() {
        
        initComponents();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1message = new javax.swing.JPanel();
        jLabel8display = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1User = new javax.swing.JTextField();
        jPasswordField1Pass = new javax.swing.JPasswordField();
        jButton1Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1user = new javax.swing.JTextField();
        jTextField2LastName = new javax.swing.JTextField();
        jTextField3Pas = new javax.swing.JTextField();
        jButton1Signup = new javax.swing.JButton();
        jButton1Exit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1Email = new javax.swing.JTextField();
        jButton1Reset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton3reset = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();
        jButton2remove = new javax.swing.JButton();
        jButton2add2 = new javax.swing.JButton();
        jButton2add3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonfill = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1reciet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1message.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1messageLayout = new javax.swing.GroupLayout(jPanel1message);
        jPanel1message.setLayout(jPanel1messageLayout);
        jPanel1messageLayout.setHorizontalGroup(
            jPanel1messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1messageLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel8display, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1messageLayout.setVerticalGroup(
            jPanel1messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1messageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8display, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1message, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 81, -1, -1));

        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 125, -1, -1));

        jTextField1User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1UserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1User, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 81, 146, -1));

        jPasswordField1Pass.setText("jPasswordField1");
        getContentPane().add(jPasswordField1Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 122, 146, -1));

        jButton1Login.setText("login");
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 183, -1, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 0, -1, -1));

        jLabel4.setText("Username:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 81, 70, 23));

        jLabel5.setText("LastName:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 122, 61, 20));

        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 160, 70, 24));
        getContentPane().add(jTextField1user, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 75, -1));

        jTextField2LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2LastNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 122, 75, -1));

        jTextField3Pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3PasActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3Pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 164, 75, -1));

        jButton1Signup.setText("Signup");
        jButton1Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SignupActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 233, -1, -1));

        jButton1Exit.setText("Exit");
        jButton1Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 183, -1, -1));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 195, 70, -1));

        jTextField1Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1EmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 195, 75, -1));

        jButton1Reset.setText("Reset");
        jButton1Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ResetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 233, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 57, 18, 250));

        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 170, 340));

        jButton3reset.setText("Reset");
        jButton3reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3resetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 90, 30));

        jButtonupdate.setText("update");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 80, 30));

        jButton2remove.setText("remove");
        jButton2remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2removeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 80, 30));

        jButton2add2.setText("Add");
        jButton2add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2add2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 80, 30));

        jButton2add3.setText("Add");
        jButton2add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2add3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 80, 30));

        jTextField1.setText("r");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 120, 40));

        jButtonfill.setText("fill");
        jButtonfill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfillActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonfill, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 413, 120, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 340, 270));

        jButton1reciet.setText("reciept");
        getContentPane().add(jButton1reciet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1UserActionPerformed
       jTextField1user.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1UserActionPerformed

    private void jButton1ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExitActionPerformed
    System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ExitActionPerformed

   @SuppressWarnings("empty-statement")
    private void jButton1SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SignupActionPerformed
        
        Password=jTextField3Pas.getText();
        Username=jTextField1user.getText();
        LastName=jTextField2LastName.getText();
        Email=jTextField1Email.getText();
     if(Password.equals("")||Username.equals("")||LastName.equals("")||Email.equals("")){
         JOptionPane.showMessageDialog(null,"Please enter a valid entry");
         
     }else{
     
     jLabel8display.setText("you sign up correcty");
      jPasswordField1Pass.setText(null);
   jTextField1Email.setText(null);
     jTextField1User.setText(null);
     jTextField1user.setText(null);
     jTextField2LastName.setText(null);
    jTextField3Pas.setText(null);
    
     
             } 
     jTextArea1.append("\nthis is agreat website"
     + "\nwe appreciate you for coming" + "\nyour name is: "+ jTextField1user.getText() 
             + "\nyour lastname is :"  + jTextField2LastName.getText());   
        
       
    }//GEN-LAST:event_jButton1SignupActionPerformed

    private void jTextField2LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2LastNameActionPerformed
       jTextField2LastName.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2LastNameActionPerformed

    private void jTextField3PasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3PasActionPerformed
       jTextField3Pas.getText(); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3PasActionPerformed

    private void jTextField1EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1EmailActionPerformed
        jTextField1Email.getText();// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1EmailActionPerformed

    private void jButton1ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ResetActionPerformed
         jPasswordField1Pass.setText(null);
   jTextField1Email.setText(null);
     jTextField1User.setText(null);
     jTextField1user.setText(null);
     jTextField2LastName.setText(null);
    jTextField3Pas.setText(null); 
jTextArea1.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ResetActionPerformed

    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed
        String ussername;
        String passsword;
        int counter=0;
         
        boolean ccorrect=false;
 ussername=jTextField1User.getText();
passsword=jPasswordField1Pass.getText();

if(ussername.equals(Username)&&passsword.equals(Password)){
    
    ccorrect=true;
    welcome hallo=new welcome();
    hallo.setVisible(true);
    
    
   
}
else{
            
   
   
    
   
    JOptionPane.showMessageDialog(null, "Incorrect credential");
   
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1LoginActionPerformed
DefaultListModel llist = new DefaultListModel();
    private void jButton3resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3resetActionPerformed
       llist.clear();
    }//GEN-LAST:event_jButton3resetActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
     int index=jList1.getSelectedIndex();
     llist.setElementAt(jTextField1.getText(), index);
     jTextField1.setText("");
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jButton2removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2removeActionPerformed
        int index=jList1.getSelectedIndex();
        llist.removeElementAt(index);
    }//GEN-LAST:event_jButton2removeActionPerformed

    private void jButton2add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2add2ActionPerformed
         llist.addElement(jTextField1.getText());
        jList1.setModel(llist);
       
    }//GEN-LAST:event_jButton2add2ActionPerformed

    private void jButton2add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2add3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2add3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String selected=jList1.getSelectedValue();
        jTextField1.setText(selected);
    }//GEN-LAST:event_jList1MouseClicked



    private void jButtonfillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfillActionPerformed
      llist.clear();
        int i;
        int randomNumber=(int)(Math.random()*1000);
       for(i=0; i<50; i++ ){
           
        llist.addElement(randomNumber);
       }
    }//GEN-LAST:event_jButtonfillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Exit;
    private javax.swing.JButton jButton1Login;
    private javax.swing.JButton jButton1Reset;
    private javax.swing.JButton jButton1Signup;
    private javax.swing.JButton jButton1reciet;
    private javax.swing.JButton jButton2add2;
    private javax.swing.JButton jButton2add3;
    private javax.swing.JButton jButton2remove;
    private javax.swing.JButton jButton3reset;
    private javax.swing.JButton jButtonfill;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8display;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1message;
    private javax.swing.JPasswordField jPasswordField1Pass;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1Email;
    private javax.swing.JTextField jTextField1User;
    private javax.swing.JTextField jTextField1user;
    private javax.swing.JTextField jTextField2LastName;
    private javax.swing.JTextField jTextField3Pas;
    // End of variables declaration//GEN-END:variables

}

