/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Search_form;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import javax.sound.sampled.*;
import javax.swing.filechooser.*;
import javax.swing.JTable;
/**
 *
 * @author desalegn
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        findUsers();
    }

   
    
public Connection getConnection(){
connection conn=null;
try{
    conn=DriverManager.getConnection("jdbc:mysql://localhost/SEARCH_TABLE","root","1527" );
    
}catch(Exception e){
    System.out.println(e.getMessage());
}
return conn;
}
public ArrayList<User> ListUsers(String valToSearch){
    ArrayList<User> usersList= new ArrayList<User>();
    Statement st=;
    ResultSet rs;
    try{
        connection conn=getConnection();
        st=conn.createConnection();
        String searchQuery="SELECT * from SEARCH_TABLE where CONCAT('id','Fname','Lname','age') LIKE '%%'";
                
        rs=st.excuteQuery(searchQuery);
        User user;
        while(rs.next()){
            user=new User(rs.getint("id"),rs.getString("fname"), rs.getString("lname"), rs.getString("age"));
            usersList.add(user);
        }
        
    }catch(Exception e){
        System.out.println(e.getMessage());
    }
    return usersList;
}
public void findUsers(){
    ArrayList<User> users=ListUsers(jTextField1.getText());
    DefaultTableModel model= new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{"id", "fname", "lname", "age"});
    
    Object[] row = new Object[4];
    for(int i=0; i<users.size(); i++){

row[0]=users.get(i).getId();
row[1]=users.get(i).getFname();
row[3]=users.get(i).getLname();
row[4]=users.get(i).getAge();
model.addRow(row);
    }
    jTable1_search.setDefaultTableModel(model);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_search = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_search = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_search.setText("Search");
        jButton1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 74, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 75, 153, -1));

        jTable1_search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "fname", "lname", "age"
            }
        ));
        jScrollPane1.setViewportView(jTable1_search);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 151, -1, 272));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_searchActionPerformed
findUsers();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_search;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_search;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
