/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ras;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import java.util.*;
import javax.swing.*;
import java.awt.PrintJob;
import javax.print.*;
import java.awt.print.*;
 import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Rasethiopia extends javax.swing.JFrame {

   
   Double pepsi = 12.00;
     
     public Double coke=3.99;
     public double mtdew=3.50;
     public double fanta=3.50;
     public double shiro=9.99;
     public double gored=10.99;
     public double kitfo=10.99;
     public double keywot=10.99;
     public double samuel=3.99;
     public double heineken=5.99;
     public double guiness=5.99;
     public double redstrip=5.99;
     public Double subttotal;
     public Double tax;
     public Double ttotal=0.00;
    
   
   
   
   
    /**
     * Creates new form 
     */
    public Rasethiopia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1kitfo = new javax.swing.JCheckBox();
        jCheckBox2keywot = new javax.swing.JCheckBox();
        jCheckBox3gored = new javax.swing.JCheckBox();
        jCheckBox4shiro = new javax.swing.JCheckBox();
        jTextField1kitfo = new javax.swing.JTextField();
        jTextField2keywot = new javax.swing.JTextField();
        jTextField3gored = new javax.swing.JTextField();
        jTextField4shirobtn = new javax.swing.JTextField();
        jTextField4shiro1 = new javax.swing.JTextField();
        foodtotalbtn = new javax.swing.JButton();
        jTextField1Qty = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1pepsi = new javax.swing.JRadioButton();
        jRadioButton2coke = new javax.swing.JRadioButton();
        jRadioButton3mtdew = new javax.swing.JRadioButton();
        jRadioButton4fanta = new javax.swing.JRadioButton();
        jTextField5pepsi = new javax.swing.JTextField();
        jTextField6coke = new javax.swing.JTextField();
        jTextField7mtdew = new javax.swing.JTextField();
        jTextField8fanta = new javax.swing.JTextField();
        drinktotalbtn2 = new javax.swing.JButton();
        jTextField4drinkbtn1 = new javax.swing.JTextField();
        jComboBox1name = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1subtotal = new javax.swing.JButton();
        jButton2tax = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3total = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton4reciept = new javax.swing.JButton();
        jButton5exit = new javax.swing.JButton();
        jButton6reset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox1redstrip = new javax.swing.JCheckBox();
        jCheckBox2samuel = new javax.swing.JCheckBox();
        jCheckBox3heineken = new javax.swing.JCheckBox();
        jCheckBox4guiness = new javax.swing.JCheckBox();
        jTextField12sam = new javax.swing.JTextField();
        jTextField13red = new javax.swing.JTextField();
        jTextField14hen = new javax.swing.JTextField();
        jTextField15guiness = new javax.swing.JTextField();
        bertotbtn = new javax.swing.JButton();
        bertottxtfld = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton1add = new javax.swing.JButton();
        jButton2remove = new javax.swing.JButton();
        jButton3print = new javax.swing.JButton();
        jTextField1bills = new javax.swing.JTextField();
        jButton3clear1 = new javax.swing.JButton();
        jButtoncash = new javax.swing.JButton();
        jLabel2message = new javax.swing.JLabel();
        jButton3range = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jCheckBox1kitfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox1kitfo.setText("ktfo");
        jCheckBox1kitfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jCheckBox1kitfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1kitfoActionPerformed(evt);
            }
        });

        jCheckBox2keywot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox2keywot.setText("keywot");
        jCheckBox2keywot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jCheckBox2keywot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2keywotActionPerformed(evt);
            }
        });

        jCheckBox3gored.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox3gored.setText("gored");
        jCheckBox3gored.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jCheckBox3gored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3goredActionPerformed(evt);
            }
        });

        jCheckBox4shiro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox4shiro.setText("shiro");
        jCheckBox4shiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jCheckBox4shiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4shiroActionPerformed(evt);
            }
        });

        jTextField1kitfo.setText("0");
        jTextField1kitfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1kitfoMouseClicked(evt);
            }
        });
        jTextField1kitfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1kitfoActionPerformed(evt);
            }
        });
        jTextField1kitfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1kitfoKeyTyped(evt);
            }
        });

        jTextField2keywot.setText("0");
        jTextField2keywot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2keywotActionPerformed(evt);
            }
        });
        jTextField2keywot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2keywotKeyTyped(evt);
            }
        });

        jTextField3gored.setText("0");
        jTextField3gored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3goredActionPerformed(evt);
            }
        });
        jTextField3gored.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3goredKeyTyped(evt);
            }
        });

        jTextField4shirobtn.setText("0");
        jTextField4shirobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4shirobtnActionPerformed(evt);
            }
        });
        jTextField4shirobtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4shirobtnKeyTyped(evt);
            }
        });

        jTextField4shiro1.setText("0");
        jTextField4shiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4shiro1ActionPerformed(evt);
            }
        });
        jTextField4shiro1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4shiro1KeyTyped(evt);
            }
        });

        foodtotalbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        foodtotalbtn.setText("foodTotal");

        jTextField1Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1QtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox4shiro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(foodtotalbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4shirobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2keywot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1kitfo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox3gored, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1kitfo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4shiro1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3gored, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2keywot, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jTextField1Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1kitfo)
                    .addComponent(jTextField1kitfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2keywot)
                    .addComponent(jTextField2keywot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3gored)
                    .addComponent(jTextField3gored, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4shiro)
                    .addComponent(jTextField4shiro1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foodtotalbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4shirobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 380));

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jRadioButton1pepsi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton1pepsi.setText("pepsi");
        jRadioButton1pepsi.setName(""); // NOI18N
        jRadioButton1pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1pepsiActionPerformed(evt);
            }
        });

        jRadioButton2coke.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton2coke.setText("coke");
        jRadioButton2coke.setName(""); // NOI18N
        jRadioButton2coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2cokeActionPerformed(evt);
            }
        });

        jRadioButton3mtdew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton3mtdew.setText("mtdew");
        jRadioButton3mtdew.setName(""); // NOI18N
        jRadioButton3mtdew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3mtdewActionPerformed(evt);
            }
        });

        jRadioButton4fanta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRadioButton4fanta.setText("fanta");
        jRadioButton4fanta.setName(""); // NOI18N
        jRadioButton4fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4fantaActionPerformed(evt);
            }
        });

        jTextField5pepsi.setText("0");
        jTextField5pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5pepsiActionPerformed(evt);
            }
        });
        jTextField5pepsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5pepsiKeyTyped(evt);
            }
        });

        jTextField6coke.setText("0");
        jTextField6coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6cokeActionPerformed(evt);
            }
        });
        jTextField6coke.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6cokeKeyTyped(evt);
            }
        });

        jTextField7mtdew.setText("0");
        jTextField7mtdew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7mtdewKeyTyped(evt);
            }
        });

        jTextField8fanta.setText("0");
        jTextField8fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8fantaActionPerformed(evt);
            }
        });
        jTextField8fanta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8fantaKeyTyped(evt);
            }
        });

        drinktotalbtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        drinktotalbtn2.setText("drinktotal");

        jTextField4drinkbtn1.setText("0");
        jTextField4drinkbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4drinkbtn1ActionPerformed(evt);
            }
        });
        jTextField4drinkbtn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4drinkbtn1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton2coke, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton3mtdew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7mtdew, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6coke, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8fanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButton1pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5pepsi))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(drinktotalbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4drinkbtn1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5pepsi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2coke, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6coke, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField7mtdew, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton3mtdew, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(drinktotalbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jTextField4drinkbtn1))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 260, 380));

        jComboBox1name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "meseret", "seam", "meserem", "etettorc" }));
        jComboBox1name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jComboBox1name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1nameMouseClicked(evt);
            }
        });
        jComboBox1name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1nameActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 80, 40));

        receipt.setBackground(new java.awt.Color(51, 0, 51));
        receipt.setColumns(20);
        receipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        receipt.setRows(5);
        receipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jScrollPane1.setViewportView(receipt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 250, 340));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("restaurant mangment system");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 30));

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));

        jButton1subtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1subtotal.setText("subtotal");
        jButton1subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1subtotalActionPerformed(evt);
            }
        });

        jButton2tax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2tax.setText("tax");
        jButton2tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2taxActionPerformed(evt);
            }
        });

        jButton3total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3total.setText("total");
        jButton3total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3totalMouseClicked(evt);
            }
        });
        jButton3total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3total)
                .addGap(18, 18, 18)
                .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3total, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 400, -1));

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));

        jButton4reciept.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4reciept.setText("reciept");
        jButton4reciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4recieptActionPerformed(evt);
            }
        });

        jButton5exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5exit.setText("exit");
        jButton5exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5exitActionPerformed(evt);
            }
        });

        jButton6reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6reset.setText("reset");
        jButton6reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jButton4reciept, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton6reset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton5exit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4reciept, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6reset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 540, -1));

        jPanel6.setBackground(new java.awt.Color(51, 0, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCheckBox1redstrip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1redstrip.setText("redstrip");
        jCheckBox1redstrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1redstripActionPerformed(evt);
            }
        });

        jCheckBox2samuel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox2samuel.setText("samuel");
        jCheckBox2samuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2samuelActionPerformed(evt);
            }
        });

        jCheckBox3heineken.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox3heineken.setText("heneiken");
        jCheckBox3heineken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3heinekenActionPerformed(evt);
            }
        });

        jCheckBox4guiness.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox4guiness.setText("guiness");
        jCheckBox4guiness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4guinessActionPerformed(evt);
            }
        });

        jTextField12sam.setText("0");
        jTextField12sam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12samKeyTyped(evt);
            }
        });

        jTextField13red.setText("0");
        jTextField13red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13redActionPerformed(evt);
            }
        });

        jTextField14hen.setText("0");

        jTextField15guiness.setText("0");

        bertotbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bertotbtn.setText("bertot");

        bertottxtfld.setText("0");
        bertottxtfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bertottxtfldActionPerformed(evt);
            }
        });
        bertottxtfld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bertottxtfldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2samuel)
                                    .addComponent(jCheckBox1redstrip))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField12sam, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jTextField13red)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(bertotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bertottxtfld))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jCheckBox3heineken))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jCheckBox4guiness)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField14hen, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextField15guiness))
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2samuel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12sam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1redstrip, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13red, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3heineken, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14hen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4guiness, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15guiness, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bertotbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(bertottxtfld))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 210, 380));

        jList2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jList2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jList2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jList2.setName("recct"); // NOI18N
        jList2.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, 250, 400));

        jButton1add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1add.setText("add");
        jButton1add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1addActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 450, 80, 40));

        jButton2remove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2remove.setText("remove");
        jButton2remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2removeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 450, -1, 40));

        jButton3print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3print.setText("print");
        jButton3print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3printActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 80, 40));

        jTextField1bills.setBackground(new java.awt.Color(51, 255, 0));
        jTextField1bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1billsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1billsMouseEntered(evt);
            }
        });
        jTextField1bills.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1billsKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1bills, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 250, 40));

        jButton3clear1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3clear1.setText("clear");
        jButton3clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3clear1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3clear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 450, 80, 40));

        jButtoncash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtoncash.setText("cash");
        jButtoncash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncashActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncash, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 490, 80, 40));

        jLabel2message.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2message.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2message.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        getContentPane().add(jLabel2message, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 270, 30));

        jButton3range.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3range.setText("range");
        jButton3range.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3rangeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3range, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 490, 80, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
DefaultListModel model=new DefaultListModel();
    private void jCheckBox1kitfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1kitfoActionPerformed
      
        String kittfo;
       kittfo = Double.toString(kitfo);
       Double qty1;
       qty1=Double.parseDouble(jTextField1Qty.getText());
       Double kitqty;
       kitqty=qty1*kitfo;
       String kitQty;
       kitQty=Double.toString(kitqty);
      
      if(jCheckBox1kitfo.isSelected()){
      jTextField1kitfo.setText(kitQty) ;
      jTextField1kitfo.setEnabled(true) ;
      model.addElement("kittfo:  "+ qty1  +  kitQty);
       
      jList2.setModel(model);
      }
         jTextField1Qty.setText("0");
          jTextField1kitfo.setText("0");
          jTextField1kitfo.setEnabled(false) ;
      
    }//GEN-LAST:event_jCheckBox1kitfoActionPerformed

    private void jCheckBox2keywotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2keywotActionPerformed
        String keywoot ;
       keywoot = Double.toString(keywot);
        if(jCheckBox2keywot.isSelected()){
        jTextField2keywot.setText(keywoot);
        jTextField2keywot.setEnabled(true);
        
        model.addElement("keywoot:"+ keywoot);
       
      jList2.setModel(model);
        }else{
           jTextField2keywot.setText("0"); 
           jTextField2keywot.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2keywotActionPerformed

    private void jCheckBox3goredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3goredActionPerformed
        String gorred;
       gorred = Double.toString(gored);
        if(jCheckBox3gored.isSelected()){
        jTextField3gored.setText(gorred);
        jTextField3gored.setEnabled(true);
         model.addElement("gorred:"+ gorred);
       
      jList2.setModel(model);
        }else{
          jTextField3gored.setText("0");  
          jTextField3gored.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3goredActionPerformed

    private void jCheckBox4shiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4shiroActionPerformed
       String shirro;
       shirro = Double.toString(shiro);
       if(jCheckBox4shiro.isSelected()){
        jTextField4shirobtn.setText(shirro);
        jTextField4shirobtn.setEnabled(true);
        model.addElement("shirro:"+ shirro);
       
      jList2.setModel(model);
       }else{
          jTextField4shirobtn.setText("0");
          jTextField4shirobtn.setEnabled(false);
       }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4shiroActionPerformed

    private void jTextField1kitfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1kitfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1kitfoActionPerformed

    private void jTextField3goredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3goredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3goredActionPerformed

    private void jTextField4shirobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4shirobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4shirobtnActionPerformed

    private void jRadioButton1pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1pepsiActionPerformed
        String pepssi;
       pepssi = Double.toString(pepsi);
        if(jRadioButton1pepsi.isSelected()){
       
            jTextField5pepsi.setEnabled(true);
            model.addElement("pepssi:"+ pepssi);
       
      jList2.setModel(model);
        }else{
            jTextField5pepsi.setText("0");
            jTextField5pepsi.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1pepsiActionPerformed

    private void jRadioButton2cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2cokeActionPerformed
        String cokke;
       cokke = Double.toString(coke);
        if(jRadioButton2coke.isSelected()){
        
            jTextField6coke.setEnabled(true);
            model.addElement("cokke:"+ cokke );
       
      jList2.setModel(model);
        }else{
            jTextField6coke.setText("0");
            jTextField6coke.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2cokeActionPerformed

    private void jRadioButton3mtdewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3mtdewActionPerformed
        String mtddew;
       mtddew = Double.toString(mtdew);
        if(jRadioButton3mtdew.isSelected()){
        jTextField7mtdew.setText(mtddew);
        jTextField7mtdew.setEnabled(true);
        model.addElement("mtddew:"+ mtddew );
       
      jList2.setModel(model);
        }else{
           jTextField7mtdew.setText("0"); 
           jTextField7mtdew.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3mtdewActionPerformed

    private void jRadioButton4fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4fantaActionPerformed
        String fannta;
       fannta = Double.toString(fanta);
        if(jRadioButton4fanta.isSelected()){
      jTextField8fanta.setText(fannta);
      jTextField8fanta.setEnabled(true);
      model.addElement("fannta:"+ fannta );
       
      jList2.setModel(model);
        }else{
            jTextField8fanta.setText("0");
            jTextField8fanta.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4fantaActionPerformed

    private void jTextField6cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6cokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6cokeActionPerformed

    private void jComboBox1nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1nameActionPerformed

    private void jTextField5pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5pepsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5pepsiActionPerformed

    private void jTextField2keywotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2keywotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2keywotActionPerformed

    private void jButton1subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1subtotalActionPerformed
      
       
   
       
     
     
     
     
     
    }//GEN-LAST:event_jButton1subtotalActionPerformed

    private void jButton2taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2taxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2taxActionPerformed
List<Double> artott=new ArrayList<>();


    private void jButton3totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3totalActionPerformed
        jTextField4shirobtn.setText("0");
        bertottxtfld.setText("0");
        jTextField4drinkbtn1.setText("0");
        Double samm;
       samm = Double.parseDouble(jTextField12sam.getText());
   
   Double redd;
       redd = Double.parseDouble(jTextField13red.getText());
    
    Double heenn;
       heenn = Double.parseDouble(jTextField14hen.getText());
    
    Double guunn;
       guunn = Double.parseDouble(jTextField15guiness.getText());
     
     Double kitt;
       kitt = Double.parseDouble(jTextField1kitfo.getText());
     
     Double keyy;
       keyy = Double.parseDouble(jTextField2keywot.getText());
     
     Double gorr;
       gorr = Double.parseDouble(jTextField3gored.getText());
     
     Double shirr;
       shirr = Double.parseDouble(jTextField4shirobtn.getText());
     
     Double pep;
       pep = Double.parseDouble(jTextField5pepsi.getText());
     
     Double cokk;
       cokk = Double.parseDouble(jTextField6coke.getText());
     
     Double mtd;
       mtd = Double.parseDouble(jTextField7mtdew.getText());
     
     Double fann;
       fann = Double.parseDouble(jTextField8fanta.getText());
       double foodTotal;
       foodTotal=keyy +gorr+shirr+kitt;
       double drinkTotal;
       drinkTotal=pep+cokk+mtd+fann;
       double bertotal;
       bertotal=samm+heenn+guunn;
       
       
     
       subttotal = foodTotal+drinkTotal+bertotal;
       String fodtot,drinktot,beertot;
       fodtot=Double.toString(foodTotal);
       String fodtoot;
       fodtoot=String.format("$%.2f",foodTotal );
       jTextField4shirobtn.setText(fodtoot);
       
       
       String drinktoot=Double.toString(drinkTotal);
       String drinnktoot;
       drinnktoot=String.format("$%.2f",drinkTotal );
       jTextField4drinkbtn1.setText(drinktoot);
       String berrtot=Double.toString(bertotal);
       String bera;
       bera=String.format("$%.2f",bertotal );
       bertottxtfld.setText(bera);
       Double itax;
       itax = 0.09;
        tax=itax*subttotal;
       
       ttotal = tax+subttotal;
       
       String sub;
       sub = Double.toString(subttotal);
       String subb;
       subb=String.format("$%.2f", subttotal);
       jTextField9.setText(subb);
       String taxi=Double.toString(tax);
       String ttaxi;
       ttaxi=String.format("$%.2f",tax );
     jTextField10.setText(ttaxi);
     String tottal;
     tottal=Double.toString(ttotal);
     String tott;
       tott=String.format("$%.2f", ttotal );
     jTextField11.setText(tott);
      model.addElement("   subtotal: "+tott);
      model.addElement("***************************");
      receipt.setText("0");
    jTextField10.setText("0");
    jTextField11.setText("0");
     jTextField12sam.setText("0");
     jTextField13red.setText("0");
     jTextField14hen.setText("0");
  jTextField15guiness.setText("0");
    jTextField1kitfo.setText("0");
    jTextField3gored.setText("0");
 jTextField4shirobtn.setText("0");
 jTextField2keywot.setText("0");
     jTextField5pepsi.setText("0");
     jTextField6coke.setText("0");
     jTextField7mtdew.setText("0");
     jTextField8fanta.setText("0");
     jTextField9.setText("0");
     receipt.setText("0");
     jTextField4shirobtn.setText("0");
     jTextField4drinkbtn1.setText("0");
     bertottxtfld.setText("0");
     jTextField1Qty.setText("0");
     jCheckBox1kitfo.setSelected(false);
    jCheckBox1redstrip.setSelected(false);
    jCheckBox2keywot.setSelected(false);
    jCheckBox2samuel.setSelected(false);
    jCheckBox3gored.setSelected(false);
     jCheckBox3heineken.setSelected(false);
    jCheckBox4guiness.setSelected(false);
    jCheckBox4shiro.setSelected(false);
    
    jRadioButton1pepsi.setSelected(false);
     jRadioButton2coke.setSelected(false);
     jRadioButton3mtdew.setSelected(false);
    jRadioButton4fanta.setSelected(false);
    
      
      
      
    }//GEN-LAST:event_jButton3totalActionPerformed

    private void jButton4recieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4recieptActionPerformed
SimpleDateFormat fformat=new SimpleDateFormat("mm-dd-yyyy  hh:mm:ss");
Date date=new Date();
 String ddate=fformat.format(date);

        receipt.append(" welcome to ras ethiopia restaurant" + "\nthe date is: " + ddate+
        "\nmy name is:" + jComboBox1name.getSelectedItem()
+ "\nsubtotal:"  + subttotal +
"\ntax:" + tax
+ "\ntotal:" + ttotal);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4recieptActionPerformed

    private void jCheckBox1redstripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1redstripActionPerformed
       String reddstrip=Double.toString(redstrip);
       if(jCheckBox1redstrip.isSelected()){
      jTextField13red.setText(reddstrip);
      jTextField13red.setEnabled(true);
      model.addElement("reddstrip:"+ redstrip );
       
      jList2.setModel(model);
       }else{
          jTextField13red.setText(""); 
          jTextField13red.setEnabled(false);
       }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1redstripActionPerformed

    private void jCheckBox3heinekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3heinekenActionPerformed
       String heinneken=Double.toString(heineken);
       if(jCheckBox3heineken.isSelected()){
      jTextField14hen.setText(heinneken);
      jTextField14hen.setEnabled(true);
      model.addElement("heinneken:"+ heineken );
       
      jList2.setModel(model);
       }else{
           jTextField14hen.setText("");
           jTextField14hen.setEnabled(false);
       }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3heinekenActionPerformed

    private void jCheckBox4guinessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4guinessActionPerformed
        String guiiness=Double.toString(guiness);
        if(jCheckBox4guiness.isSelected()){
      jTextField15guiness.setText(guiiness);
      jTextField15guiness.setEnabled(true);
      jTextField15guiness.setEnabled(false);
      model.addElement("guiiness:"+ guiness );
       
      jList2.setModel(model);
        }else{
           jTextField15guiness.setText(""); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4guinessActionPerformed

    private void jCheckBox2samuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2samuelActionPerformed
      String sammuel=Double.toString(samuel);
      if(jCheckBox2samuel.isSelected()){
      jTextField12sam.setText(sammuel);
      jTextField12sam.setEnabled(true);
      jTextField12sam.setEnabled(false);
      model.addElement("sammuel:  "+ samuel );
       
      jList2.setModel(model);
      }else{
       jTextField12sam.setText("");
      }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2samuelActionPerformed

    private void jButton5exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5exitActionPerformed
int iExit=JOptionPane.showConfirmDialog(null, "do you want to exit?", "exit",JOptionPane.YES_NO_OPTION ) ; 
if(iExit==JOptionPane.YES_OPTION){
System.exit(1);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5exitActionPerformed

    private void jTextField1kitfoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1kitfoKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);      
      
       // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1kitfoKeyTyped

    private void jTextField2keywotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2keywotKeyTyped
 keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);
     // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2keywotKeyTyped

    private void jButton6resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6resetActionPerformed
        receipt.setText("0");
    jTextField10.setText("0");
    jTextField11.setText("0");
     jTextField12sam.setText("0");
     jTextField13red.setText("0");
     jTextField14hen.setText("0");
  jTextField15guiness.setText("0");
    jTextField1kitfo.setText("0");
    jTextField3gored.setText("0");
 jTextField4shirobtn.setText("0");
 jTextField2keywot.setText("0");
     jTextField5pepsi.setText("0");
     jTextField6coke.setText("0");
     jTextField7mtdew.setText("0");
     jTextField8fanta.setText("0");
     jTextField9.setText("0");
     receipt.setText("0");
     jTextField4shirobtn.setText("0");
     jTextField4drinkbtn1.setText("0");
     bertottxtfld.setText("0");
     jTextField1Qty.setText("0");
     jCheckBox1kitfo.setSelected(false);
    jCheckBox1redstrip.setSelected(false);
    jCheckBox2keywot.setSelected(false);
    jCheckBox2samuel.setSelected(false);
    jCheckBox3gored.setSelected(false);
     jCheckBox3heineken.setSelected(false);
    jCheckBox4guiness.setSelected(false);
    jCheckBox4shiro.setSelected(false);
    
    jRadioButton1pepsi.setSelected(false);
     jRadioButton2coke.setSelected(false);
     jRadioButton3mtdew.setSelected(false);
    jRadioButton4fanta.setSelected(false);
    
    // End of variables declaration           // TODO add your handling code here:
    }//GEN-LAST:event_jButton6resetActionPerformed

    private void jTextField1kitfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1kitfoMouseClicked
 ; 
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1kitfoMouseClicked

    private void jTextField8fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8fantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8fantaActionPerformed

    private void jTextField3goredKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3goredKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3goredKeyTyped

    private void jTextField4shirobtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4shirobtnKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4shirobtnKeyTyped

    private void jTextField5pepsiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5pepsiKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5pepsiKeyTyped

    private void jTextField6cokeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6cokeKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6cokeKeyTyped

    private void jTextField7mtdewKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7mtdewKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7mtdewKeyTyped

    private void jTextField8fantaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8fantaKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8fantaKeyTyped

    private void jTextField12samKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12samKeyTyped
keyPreessed imt=new keyPreessed();
      
      imt.evtPressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12samKeyTyped

    private void jTextField13redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13redActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13redActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       receipt.setEnabled(false);
    jTextField10.setEnabled(false);
    jTextField11.setEnabled(false);
     jTextField12sam.setEnabled(false);
     jTextField13red.setEnabled(false);
     jTextField14hen.setEnabled(false);
  jTextField15guiness.setEnabled(false);
    jTextField1kitfo.setEnabled(false);
    jTextField3gored.setEnabled(false);
 jTextField4shirobtn.setEnabled(false);
 jTextField2keywot.setEnabled(false);
     jTextField5pepsi.setEnabled(false);
     jTextField6coke.setEnabled(false);
     jTextField7mtdew.setEnabled(false);
     jTextField8fanta.setEnabled(false);
     jTextField9.setEnabled(false);
     receipt.setEnabled(false);
     jTextField1Qty.setBackground(Color.red);
     
     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox1nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1nameMouseClicked
       
    }//GEN-LAST:event_jComboBox1nameMouseClicked

    private void jTextField4shiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4shiro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4shiro1ActionPerformed

    private void jTextField4shiro1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4shiro1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4shiro1KeyTyped

    private void jTextField4drinkbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4drinkbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4drinkbtn1ActionPerformed

    private void jTextField4drinkbtn1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4drinkbtn1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4drinkbtn1KeyTyped

    private void bertottxtfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bertottxtfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bertottxtfldActionPerformed

    private void bertottxtfldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bertottxtfldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_bertottxtfldKeyTyped

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton2removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2removeActionPerformed

        model.remove(jList2.getSelectedIndex());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2removeActionPerformed

    private void jButton3printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3printActionPerformed
       try {
           receipt.print();
       } catch (PrinterException ex) {
           Logger.getLogger(Rasethiopia.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_jButton3printActionPerformed
Double sum=0.00;
    private void jButton1addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1addActionPerformed
      
        for(Double i :artott){
          sum+=i;
      
       
      
      }
       String arsum=Double.toString(sum);
      model.addElement("    totaal :"+arsum);
      
      
     
    }//GEN-LAST:event_jButton1addActionPerformed

    private void jButton3totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3totalMouseClicked
      artott.add(ttotal); 
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3totalMouseClicked

    private void jButton3clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3clear1ActionPerformed
     model.clear(); 
     jTextField1bills.setText("0");   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3clear1ActionPerformed

    private void jButtoncashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncashActionPerformed
     if("".equals(jTextField1bills.getText()) ){
         jLabel2message.setText("invalid entry");
     }if(Double.parseDouble(jTextField1bills.getText()) < sum){
      jLabel2message.setText("wrong amount!");  
      jTextField1bills.setText("0"); 
    }
     
     else{
        Double change=Double.parseDouble(jTextField1bills.getText())-sum;
    String cchange=Double.toString(change);
   
    String negate="Remainning:   "+cchange;
    
    model.addElement(negate.toUpperCase());
    
     }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncashActionPerformed

    private void jTextField1billsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1billsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1billsKeyPressed

    private void jTextField1billsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1billsMouseClicked
       jLabel2message.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1billsMouseClicked

    private void jTextField1billsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1billsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1billsMouseEntered

    private void jButton3rangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3rangeActionPerformed
       int index1 =model.indexOf(evt, WIDTH) ;
       int index2 = model.indexOf(evt, WIDTH) ;
        model.removeRange(index1, index2);
    }//GEN-LAST:event_jButton3rangeActionPerformed

    private void jTextField1QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1QtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> {
            new Rasethiopia().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bertotbtn;
    private javax.swing.JTextField bertottxtfld;
    private javax.swing.JButton drinktotalbtn2;
    private javax.swing.JButton foodtotalbtn;
    private javax.swing.JButton jButton1add;
    private javax.swing.JButton jButton1subtotal;
    private javax.swing.JButton jButton2remove;
    private javax.swing.JButton jButton2tax;
    private javax.swing.JButton jButton3clear1;
    private javax.swing.JButton jButton3print;
    private javax.swing.JButton jButton3range;
    private javax.swing.JButton jButton3total;
    private javax.swing.JButton jButton4reciept;
    private javax.swing.JButton jButton5exit;
    private javax.swing.JButton jButton6reset;
    private javax.swing.JButton jButtoncash;
    private javax.swing.JCheckBox jCheckBox1kitfo;
    private javax.swing.JCheckBox jCheckBox1redstrip;
    private javax.swing.JCheckBox jCheckBox2keywot;
    private javax.swing.JCheckBox jCheckBox2samuel;
    private javax.swing.JCheckBox jCheckBox3gored;
    private javax.swing.JCheckBox jCheckBox3heineken;
    private javax.swing.JCheckBox jCheckBox4guiness;
    private javax.swing.JCheckBox jCheckBox4shiro;
    private javax.swing.JComboBox<String> jComboBox1name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2message;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1pepsi;
    private javax.swing.JRadioButton jRadioButton2coke;
    private javax.swing.JRadioButton jRadioButton3mtdew;
    private javax.swing.JRadioButton jRadioButton4fanta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12sam;
    private javax.swing.JTextField jTextField13red;
    private javax.swing.JTextField jTextField14hen;
    private javax.swing.JTextField jTextField15guiness;
    private javax.swing.JTextField jTextField1Qty;
    private javax.swing.JTextField jTextField1bills;
    private javax.swing.JTextField jTextField1kitfo;
    private javax.swing.JTextField jTextField2keywot;
    private javax.swing.JTextField jTextField3gored;
    private javax.swing.JTextField jTextField4drinkbtn1;
    private javax.swing.JTextField jTextField4shiro1;
    private javax.swing.JTextField jTextField4shirobtn;
    private javax.swing.JTextField jTextField5pepsi;
    private javax.swing.JTextField jTextField6coke;
    private javax.swing.JTextField jTextField7mtdew;
    private javax.swing.JTextField jTextField8fanta;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea receipt;
    // End of variables declaration//GEN-END:variables

    private void elsif(boolean par) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
